### ISSUE TITLE
Anyone else experiencing below error when running pip install dj-static

### ISSUE THREAD

**Issue by ogiaquino** [kennethreitz/dj-static#21]
Downloading/unpacking dj-static
  Running setup.py egg_info for package dj-static
    
Downloading/unpacking static (from dj-static)
  Running setup.py egg_info for package static
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/home/ogi/virtualenv/trypviewer/build/static/setup.py", line 7, in <module>
        with open('README.md') as readme_file:
    IOError: [Errno 2] No such file or directory: 'README.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/home/ogi/virtualenv/trypviewer/build/static/setup.py", line 7, in <module>

    with open('README.md') as readme_file:

IOError: [Errno 2] No such file or directory: 'README.md'

**Comment by flevour** [comment]
hi @ogiaquino is this still an issue? If positive, could you provide more information to reproduce such as system/pip version etc?
